services:
  # databases
  core-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: core_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - core_data:/var/lib/postgresql/data
  user-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: user_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - users_data:/var/lib/postgresql/data
  it-provision-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: it_provision_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - it_provision_data:/var/lib/postgresql/data
  notification-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: notification_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - notification_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  jaeger:
    image: jaegertracing/jaeger:latest
    command: ["--query.base-path=/jaeger"]
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"


  # application services
  users:
    image: internship-tracker/user-service:${APP_TAG:-latest}
    build:
      context: .
      dockerfile: src/UserService/UserService.Api/Dockerfile
    depends_on:
      user-db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      jaeger:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__UsersDb: "Host=user-db;Port=5432;Database=user_db;Username=postgres;Password=Password123!"
      RabbitMQ__Host: "rabbitmq"
      RabbitMQ__Username: ${RABBITMQ_USER}
      RabbitMQ__Password: ${RABBITMQ_PASS}
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "user-service"
  core:
    image: internship-tracker/core-service:${APP_TAG:-latest}
    build:
      context: .
      dockerfile: src/CoreService/CoreService.Api/Dockerfile
    depends_on:
      core-db:
        condition: service_healthy
      users:
        condition: service_started
      rabbitmq:
        condition: service_started
      it-provision:
        condition: service_started
      notification:
        condition: service_started
      jaeger:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__CoreDb: "Host=core-db;Port=5432;Database=core_db;Username=postgres;Password=Password123!"
      UserService__BaseUrl: "http://users:8080"
      RabbitMQ__Host: "rabbitmq"
      RabbitMQ__Username: ${RABBITMQ_USER}
      RabbitMQ__Password: ${RABBITMQ_PASS}
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "core-service"
  it-provision:
    image: internship-tracker/it-provision-service:${APP_TAG:-latest}
    build:
      context: .
      dockerfile: src/ITProvisionService/ITProvisionService.Api/Dockerfile
    depends_on:
      it-provision-db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      jaeger:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__ITProvisionDb: "Host=it-provision-db;Port=5432;Database=it_provision_db;Username=postgres;Password=Password123!"
      RabbitMQ__Host: "rabbitmq"
      RabbitMQ__Username: ${RABBITMQ_USER}
      RabbitMQ__Password: ${RABBITMQ_PASS}
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "it-provision-service"
  notification:
    image: internship-tracker/notification-service:${APP_TAG:-latest}
    build:
      context: .
      dockerfile: src/NotificationService/NotificationService.Api/Dockerfile
    depends_on:
      notification-db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      jaeger:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__NotificationDb: "Host=notification-db;Port=5432;Database=notification_db;Username=postgres;Password=Password123!"
      RabbitMQ__Host: "rabbitmq"
      RabbitMQ__Username: ${RABBITMQ_USER}
      RabbitMQ__Password: ${RABBITMQ_PASS}
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "notification-service"
  gateway:
    image: internship-tracker/gateway-service:${APP_TAG:-latest}
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    depends_on:
        - core
        - users
        - it-provision
        - notification
        - jaeger
    ports:
      - "8000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ReverseProxy__Clusters__core__Destinations__default__Address: "http://core:8080"
      ReverseProxy__Clusters__users__Destinations__default__Address: "http://users:8080"
      ReverseProxy__Clusters__it-provision__Destinations__default__Address: "http://it-provision:8080"
      ReverseProxy__Clusters__notification__Destinations__default__Address: "http://notification:8080"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "gateway-service"

volumes:
  core_data:
  users_data:
  it_provision_data:
  notification_data:
  rabbitmq_data:
