apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-service
  namespace: internship-tracker
  labels:
    app: core-service
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: core-service
  template:
    metadata:
      labels:
        app: core-service
    spec:
      containers:
        - name: core-service
          image: internship-tracker/core-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CORE_CONNECTION_STRING
            - name: RabbitMQ__Host
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RabbitMQ__Host
            - name: RabbitMQ__Username
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RabbitMQ__Username
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RabbitMQ__Password
            - name: UsersService__BaseUrl
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: UsersService__BaseUrl
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ASPNETCORE_ENVIRONMENT
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: OTEL_EXPORTER_OTLP_ENDPOINT
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: OTEL_EXPORTER_OTLP_PROTOCOL
            - name: OTEL_SERVICE_NAME
              value: "core-service"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: internship-tracker
spec:
  selector:
    app: core-service
  ports:
    - port: 8080
      targetPort: 8080