apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- rabbitmq.yaml
- postgres-core.yaml
- postgres-users.yaml
- postgres-it-provision.yaml
- postgres-notification.yaml
- core-service.yaml
- user-service.yaml
- it-provision-service.yaml
- notification-service.yaml
- gateway-service.yaml
- ingress.yaml
images:
- name: internship-tracker/core-service
  newName: internship-tracker/core-service
  newTag: v1.0.1-3a45d48
- name: internship-tracker/gateway-service
  newName: internship-tracker/gateway-service
  newTag: v1.0.1-3a45d48
- name: internship-tracker/it-provision-service
  newName: internship-tracker/it-provision-service
  newTag: v1.0.1-3a45d48
- name: internship-tracker/notification-service
  newName: internship-tracker/notification-service
  newTag: v1.0.1-3a45d48
- name: internship-tracker/user-service
  newName: internship-tracker/user-service
  newTag: v1.0.1-3a45d48
