apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - rabbitmq.yaml
  - postgres-core.yaml
  - postgres-users.yaml
  - postgres-it-provision.yaml
  - postgres-notification.yaml
  - core-service.yaml
  - user-service.yaml
  - it-provision-service.yaml
  - notification-service.yaml
  - gateway-service.yaml
  - ingress.yaml
