apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: internship-tracker
type: Opaque
stringData:
  RabbitMQ__Password: "guest"
  CORE_CONNECTION_STRING: "Host=postgres-core;Port=5432;Database=core_db;Username=postgres;Password=Password123!"
  USERS_CONNECTION_STRING: "Host=postgres-users;Port=5432;Database=users_db;Username=postgres;Password=Password123!"
  IT_PROVISION_CONNECTION_STRING: "Host=postgres-it-provision;Port=5432;Database=it_provision_db;Username=postgres;Password=Password123!"
  NOTIFICATION_CONNECTION_STRING: "Host=postgres-notification;Port=5432;Database=notification_db;Username=postgres;Password=Password123!"
  POSTGRES_PASSWORD: "Password123!"